[tool.poetry]
name = "schwifly"
version = "0.1.0"
description = ""
authors = ["Alex Jenkins <alex@alexleejenkins.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
browser-use = "^0.9.6"
playwright = "^1.40.0"
fastapi = "^0.121.2"
pydantic = "^2.0.0"
uvicorn = {extras = ["standard"], version = "^0.27.0"}
python-dotenv = "^1.0.0"
typer = "^0.20.0"
rich = "^14.2.0"
termcolor = "^3.2.0"



[tool.poetry.scripts]
schwifly = "schwifly.cli:app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
