import { test } from '@playwright/test';
import { fileURLToPath } from 'node:url';
import { step } from '../src/workflow';
import { EscalatingResolver } from '../src/heal';
import { openSharedSession, type SharedSession } from '../src/sharedCdp';

// Generated by `schwifly gen` from a user story. A Workflow is a real Playwright spec:
// deterministic-first, each step tries its locator and the AI backup only heals on failure,
// then `schwifly run` writes the healed locator back into this file.
const here = fileURLToPath(import.meta.url);

// Outcome contract (ticket): Add an element to the list. Delete
//   must hold: the page shows Delete

test.describe('attempt add element', () => {
  test.setTimeout(120_000);

  let session: SharedSession;
  test.beforeAll(async () => {
    session = await openSharedSession();
  });
  test.afterAll(async () => {
    await session?.close();
  });

  test('attempt add element', async () => {
    const { page, stagehand } = session;
    // SCHWIFLY_NO_HEAL=1 disables the AI backup for one run. The attempt flow's certification
    // replay sets it so a capture cannot certify itself by healing an inaccurate locator.
    const heal = process.env.SCHWIFLY_NO_HEAL === '1' ? undefined : new EscalatingResolver(stagehand);
    await page.goto('https://the-internet.herokuapp.com/add_remove_elements/');
    await step(page, { intent: 'click the button to add an element', locator: 'role=button[name="Add Element"i]', action: 'click' }, { resolver: heal, file: here });
    await step(page, { intent: 'the page shows Delete', locator: 'role=button[name="Delete"i]', action: 'expectText', value: 'Delete' }, { resolver: heal, file: here });
  });
});
