import { test } from '@playwright/test';
import { fileURLToPath } from 'node:url';
import { step } from '../src/workflow';
import { EscalatingResolver } from '../src/heal';
import { openSharedSession, type SharedSession } from '../src/sharedCdp';

// Generated by `schwifly gen` from a user story. A Workflow is a real Playwright spec:
// deterministic-first, each step tries its locator and the AI backup only heals on failure,
// then `schwifly run` writes the healed locator back into this file.
const here = fileURLToPath(import.meta.url);

test.describe('generated workflow', () => {
  test.setTimeout(120_000);

  let session: SharedSession;
  test.beforeAll(async () => {
    session = await openSharedSession();
  });
  test.afterAll(async () => {
    await session?.close();
  });

  test('generated workflow', async () => {
    const { page, stagehand } = session;
    const heal = new EscalatingResolver(stagehand);
    await page.goto('https://vercel.com/');
    await step(page, { intent: 'Open the pricing page', locator: 'xpath=/html[1]/body[1]/div[2]/div[1]/header[1]/div[1]/nav[1]/div[1]/a[2]', action: 'click' }, { resolver: heal, file: here, stepLog: '.schwifly/steps.ndjson' });
    await step(page, { intent: 'See the Hobby plan price is 0', locator: 'xpath=/html[1]/body[1]/div[2]/div[1]/main[1]/div[1]/section[2]/div[1]/div[1]/div[2]/span[1]', action: 'expectVisible' }, { resolver: heal, file: here, stepLog: '.schwifly/steps.ndjson' });
    await step(page, { intent: 'See the Pro plan price is 20 per month', locator: 'xpath=/html[1]/body[1]/div[2]/div[1]/main[1]/div[1]/section[2]/div[1]/div[2]/div[2]/span[1]', action: 'expectVisible' }, { resolver: heal, file: here, stepLog: '.schwifly/steps.ndjson' });
    await step(page, { intent: 'the page shows 0', locator: 'xpath=/html[1]/body[1]/div[2]/div[1]/main[1]/div[1]/section[2]/div[1]/div[1]/div[2]/span[1]', action: 'expectText', value: '0' }, { resolver: heal, file: here, stepLog: '.schwifly/steps.ndjson' });
    await step(page, { intent: 'the page shows 20', locator: 'xpath=/html[1]/body[1]/div[2]/div[1]/main[1]/div[1]/section[2]/div[1]/div[2]/div[2]/span[1]', action: 'expectText', value: '20' }, { resolver: heal, file: here, stepLog: '.schwifly/steps.ndjson' });
  });
});
