import type { Action } from './workflow';

// Render a healable workflow .spec.ts in the EXACT byte-shape of workflows/example.spec.ts:
// the same imports, `const here = fileURLToPath(import.meta.url)`, and `file: here` on every
// step (so a heal can write the new locator back into THIS generated file). The template is
// load-bearing -- the resolver seam, the write-back, and the diff all assume this shape.

export interface EmitStep {
  intent: string;
  locator: string;          // plain-string selector (CSS / text= / role= / [aria-label] / xpath=)
  action: Action;
  value?: string;           // for 'fill' and 'expectText'
}

export interface EmitAssertion {
  type: 'exact' | 'semantic';
  value: string;            // the <validate> text
  intent: string;           // what is being validated, e.g. "the Pro price is 19"
  locator: string;          // discovered selector for the element under assertion
}

export interface EmitSpec {
  title: string;
  url: string;
  steps: EmitStep[];
  assertions: EmitAssertion[];
}

// JS single-quoted string literal with the quote/backslash escaped -- locators and intents
// are plain strings, never chained getByRole(...) objects (that would break write-back + diff).
function q(s: string): string {
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function stepLine(s: EmitStep): string {
  const fields = [`intent: ${q(s.intent)}`, `locator: ${q(s.locator)}`, `action: ${q(s.action)}`];
  if (s.value !== undefined) fields.push(`value: ${q(s.value)}`);
  return `  await step(page, { ${fields.join(', ')} }, { resolver: heal, file: here, stepLog: '.schwifly/steps.ndjson' });`;
}

export function emit(spec: EmitSpec): string {
  // Each <validate> becomes an expectText step (epic 5), appended after the navigation steps.
  const assertSteps: EmitStep[] = spec.assertions.map((a) => ({
    intent: a.intent,
    locator: a.locator,
    action: 'expectText',
    value: a.value,
  }));
  const body = [...spec.steps, ...assertSteps].map(stepLine).join('\n');

  return `import { test } from '@playwright/test';
import { fileURLToPath } from 'node:url';
import { step } from '../src/workflow';
import { PlaywrightHeuristicResolver } from '../src/heal';

// Generated by \`schwifly gen\` from a user story. A Workflow is a real Playwright spec:
// deterministic-first, each step tries its locator and the AI backup only heals on failure,
// then \`schwifly run\` writes the healed locator back into this file.
const heal = new PlaywrightHeuristicResolver();
const here = fileURLToPath(import.meta.url);

test(${q(spec.title)}, async ({ page }) => {
  await page.goto(${q(spec.url)});
${body}
});
`;
}
