import type { Action } from './workflow';

// Render a healable workflow .spec.ts in the EXACT byte-shape of workflows/example.spec.ts:
// the same imports, `const here = fileURLToPath(import.meta.url)`, and `file: here` on every
// step (so a heal can write the new locator back into THIS generated file). The template is
// load-bearing -- the resolver seam, the write-back, and the diff all assume this shape.

export interface EmitStep {
  intent: string;
  locator: string;          // plain-string selector (CSS / text= / role= / [aria-label] / xpath=)
  action: Action;
  value?: string;           // for 'fill' and 'expectText'
}

export interface EmitAssertion {
  type: 'exact' | 'semantic';
  value: string;            // the <validate> text
  intent: string;           // what is being validated, e.g. "the Pro price is 19"
  locator: string;          // discovered selector for the element under assertion
}

export interface EmitSpec {
  title: string;
  url: string;
  steps: EmitStep[];
  assertions: EmitAssertion[];
  /** Stated outcome the assertions below encode, rendered as a header comment (attempt flow). */
  contract?: { summary: string; checks: string[]; source: string };
}

// JS single-quoted string literal with the quote/backslash escaped -- locators and intents
// are plain strings, never chained getByRole(...) objects (that would break write-back + diff).
// Exported so write-back (applyHeal) anchors on the SAME `locator: '...'` byte-shape emit wrote.
export function q(s: string): string {
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function stepLine(s: EmitStep): string {
  const fields = [`intent: ${q(s.intent)}`, `locator: ${q(s.locator)}`, `action: ${q(s.action)}`];
  if (s.value !== undefined) fields.push(`value: ${q(s.value)}`);
  return `    await step(page, { ${fields.join(', ')} }, { resolver: heal, file: here });`;
}

export function emit(spec: EmitSpec): string {
  // Each <validate> becomes an expectText step (epic 5), appended after the navigation steps.
  const assertSteps: EmitStep[] = spec.assertions.map((a) => ({
    intent: a.intent,
    locator: a.locator,
    action: 'expectText',
    value: a.value,
  }));
  const body = [...spec.steps, ...assertSteps].map(stepLine).join('\n');

  // The outcome contract, verbatim in the file: a human reading this spec can see what "success"
  // means without rerunning anything, and can check that the assertions below actually encode it.
  const contract = spec.contract
    ? `\n// Outcome contract (${spec.contract.source}): ${spec.contract.summary}\n` +
      spec.contract.checks.map((c) => `//   must hold: ${c}`).join('\n') +
      '\n'
    : '';

  // Runs over the shared-CDP session (Stagehand owns Chromium, Playwright attaches over CDP) so a
  // heal's observe() and step()'s locators drive the SAME DOM, and the LLM heal tier
  // (EscalatingResolver) is reachable -- the heuristic alone cannot resolve descriptive intents.
  // Always-launch: every `schwifly run` opens the shared session in beforeAll, so it pays a second
  // Chromium launch whether or not a heal fires (the "AI only on failure" cost model is traded for
  // a reachable heal tier). Mirrors tests/live-tier2.spec.ts.
  return `import { test } from '@playwright/test';
import { fileURLToPath } from 'node:url';
import { step } from '../src/workflow';
import { EscalatingResolver } from '../src/heal';
import { openSharedSession, type SharedSession } from '../src/sharedCdp';

// Generated by \`schwifly gen\` from a user story. A Workflow is a real Playwright spec:
// deterministic-first, each step tries its locator and the AI backup only heals on failure,
// then \`schwifly run\` writes the healed locator back into this file.
const here = fileURLToPath(import.meta.url);
${contract}
test.describe(${q(spec.title)}, () => {
  test.setTimeout(120_000);

  let session: SharedSession;
  test.beforeAll(async () => {
    session = await openSharedSession();
  });
  test.afterAll(async () => {
    await session?.close();
  });

  test(${q(spec.title)}, async () => {
    const { page, stagehand } = session;
    // SCHWIFLY_NO_HEAL=1 disables the AI backup for one run. The attempt flow's certification
    // replay sets it so a capture cannot certify itself by healing an inaccurate locator.
    const heal = process.env.SCHWIFLY_NO_HEAL === '1' ? undefined : new EscalatingResolver(stagehand);
    await page.goto(${q(spec.url)});
${body}
  });
});
`;
}
